name = "deciply"
main = ".open-next/worker.js"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "deciply.com/*", zone_name = "deciply.com" },
  { pattern = "www.deciply.com/*", zone_name = "deciply.com" }
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
